# Eureka properties
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

# Server properties
server:
  port: 8095

# Application properties
spring:
  application:
    name: SHOP-SERVICE
# MongoDB properties
  data:
    mongodb:
      database: testWorkingDB
      host: localhost
      port: 27017
