# Test environment
#mongodb_hostname: shop-db
#mongodb_database_name: testShopDB

# Server properties
server:
  port: 8095

# Application properties
spring:
  application:
    name: SHOP-SERVICE
# MongoDB properties
  data:
    mongodb:
      database: ${mongodb_database_name}
      host: ${mongodb_hostname}
      port: 27017
  config:
    import: optional:settings.yml
  profiles:
    active: standalone
