# Eureka properties
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    hostname: localhost

# Server properties
server:
  port: 8080

# Application properties
spring:
  application:
    name: SHOP-SERVICE
# MongoDB properties
  data:
    mongodb:
      database: testWorkingDB
      host: shop-db
      port: 27017
